[package]
name = "cream"
version = "0.5.0"
authors = ["Chuck <cdriesler.iv@gmail.com>"]
description = "Geometry library for svgar"
license = "AGPL-3.0"
repository = "https://github.com/cdriesler/svgar"

[lib]
crate-type = ["cdylib"]
path = "src/rs/lib.rs"

[dependencies]
wasm-bindgen = "0.2"

