name: build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14]
        rust-version: [stable]
  
    steps:
    - uses: actions/checkout@v1
    - name: Initialize node.js 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Initialize rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust-version }}
    - name: Install dependencies
      run: npm install
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build for deploy
      run: npm run build